<?php
return [
	'courses/show' => 'courses/show',
	'courses/add' => 'courses/add',
	'courses/edit' => 'courses/edit',
	'courses/delete' => 'courses/delete',
	'courses/single' => 'courses/single',
	'groups/show' => 'groups/show',
	'groups/add' => 'groups/add',
	'groups/edit' => 'groups/edit',
	'groups/delete' => 'groups/delete',
	'groups/single' => 'groups/single',
	'students/show' => 'students/show',
	'students/add' => 'students/add',
	'students/edit' => 'students/edit',
	'students/delete' => 'students/delete',
	'students/single' => 'students/single',
	'lessons/show' => 'lessons/show',
	'lessons/add' => 'lessons/add',
	'lessons/edit' => 'lessons/edit',
	'lessons/delete' => 'lessons/delete',
	'lessons/single' => 'lessons/single',
	'marks/show' => 'marks/show',
	'marks/add' => 'marks/add',
	'marks/edit' => 'marks/edit',
	'marks/delete' => 'marks/delete',
	'marks/single' => 'marks/single',
	'diplomas/show' => 'diplomas/show',
	'diplomas/add' => 'diplomas/add',
	'diplomas/edit' => 'diplomas/edit',
	'diplomas/delete' => 'diplomas/delete',
	'diplomas/single' => 'diplomas/single'
];